"""
demo_builder.py — turn a game concept into a runnable Godot 4 skeleton.

Takes a ``GameConcept`` (game_concept.py) and produces a Godot 4
project directory with:

  • project.godot manifest
  • A main scene (.tscn) sized to the genre (platformer / top-down /
    puzzle / VN / etc. — see ``GENRE_TEMPLATES``)
  • A main.gd script stub the player can already run
  • icon.svg placeholder so Godot doesn't yell about a missing icon
  • README.md describing the concept and the TODO list

Output lives at ``vault/projects/<slug>/`` so the user can open it
in the Godot Workspace tab and hit Run within seconds.

The skeleton is intentionally minimal — enough to launch without
errors and show *something* on screen, with TODO markers exactly
where the user (or the GodotCoder) should fill in the next layer
of detail. We do NOT try to ship a finished game here; that's the
user + Coder agent's job.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


# ============================================================
# Result type
# ============================================================

@dataclass
class DemoBuildResult:
    """Outcome of one demo build."""
    project_path:    Optional[Path] = None
    files_written:   List[Path] = field(default_factory=list)
    notes:           List[str] = field(default_factory=list)
    error:           str = ""

    @property
    def ok(self) -> bool:
        return self.project_path is not None and not self.error


# ============================================================
# Genre → skeleton template selection
# ============================================================

# Map common genre strings (case-insensitive substring match) to a
# template name. The first matching template wins. The fallback is
# "generic" — a single Node2D with a label.
GENRE_TEMPLATES: Tuple[Tuple[str, str], ...] = (
    ("platformer",       "platformer"),
    ("metroidvania",     "platformer"),
    ("puzzle-platformer","platformer"),
    ("top-down",         "topdown"),
    ("twin-stick",       "topdown"),
    ("shooter",          "topdown"),
    ("roguelike",        "topdown"),
    ("rpg",              "topdown"),
    ("visual novel",     "vn"),
    ("vn",               "vn"),
    ("walking sim",      "vn"),
    ("puzzle",           "puzzle"),
    ("deck",             "puzzle"),
    ("management",       "puzzle"),
    ("city builder",     "puzzle"),
)


def _pick_template(genre: str) -> str:
    g = (genre or "").lower()
    for needle, tpl in GENRE_TEMPLATES:
        if needle in g:
            return tpl
    return "generic"


# ============================================================
# Static assets (kept inline so demo_builder is self-contained)
# ============================================================

# Minimal valid Godot icon.svg — a tiny solid square. Avoids the
# "no icon configured" warning on first launch.
_ICON_SVG = '''<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg">
<rect width="128" height="128" fill="#d32f2f"/>
</svg>'''


def _project_godot(concept_title: str, main_scene: str) -> str:
    """Render the project.godot manifest. Format 5 is Godot 4.x."""
    return (
        "; Engine configuration file.\n"
        "; Generated by Anvil demo_builder.\n"
        "\n"
        "config_version=5\n"
        "\n"
        "[application]\n"
        f'config/name="{concept_title}"\n'
        f'run/main_scene="{main_scene}"\n'
        'config/features=PackedStringArray("4.2", "GL Compatibility")\n'
        'config/icon="res://icon.svg"\n'
        "\n"
        "[rendering]\n"
        'renderer/rendering_method="gl_compatibility"\n'
        'renderer/rendering_method.mobile="gl_compatibility"\n'
    )


# ============================================================
# Per-genre skeletons
# ============================================================
#
# Each template returns a list of (relative_path, content_string)
# pairs. Path strings use forward slashes; we normalise when writing.

def _tpl_platformer(concept) -> List[Tuple[str, str]]:
    main_tscn = (
        '[gd_scene load_steps=2 format=3]\n'
        '\n'
        '[ext_resource type="Script" path="res://main.gd" id="1_main"]\n'
        '\n'
        '[node name="Main" type="Node2D"]\n'
        'script = ExtResource("1_main")\n'
        '\n'
        '[node name="Label" type="Label" parent="."]\n'
        'offset_left = 20.0\n'
        'offset_top = 20.0\n'
        'offset_right = 400.0\n'
        'offset_bottom = 80.0\n'
        f'text = "{concept.display_title}"\n'
        '\n'
        '[node name="Floor" type="StaticBody2D" parent="."]\n'
        'position = Vector2(0, 500)\n'
        '\n'
        '[node name="Shape" type="CollisionShape2D" parent="Floor"]\n'
        '\n'
        '[node name="Player" type="CharacterBody2D" parent="."]\n'
        'position = Vector2(200, 300)\n'
        '\n'
        '[node name="Sprite" type="ColorRect" parent="Player"]\n'
        'offset_left = -16.0\n'
        'offset_top = -16.0\n'
        'offset_right = 16.0\n'
        'offset_bottom = 16.0\n'
        'color = Color(0.83, 0.18, 0.18, 1)\n'
        '\n'
        '[node name="Collision" type="CollisionShape2D" parent="Player"]\n'
    )
    main_gd = (
        '# main.gd — Platformer skeleton\n'
        f'# Concept: {concept.display_title}\n'
        f'# Genre:   {concept.genre or "Platformer"}\n'
        f'# Hook:    {concept.hook}\n'
        '\n'
        'extends Node2D\n'
        '\n'
        '@export var move_speed: float = 200.0\n'
        '@export var jump_velocity: float = -400.0\n'
        '@export var gravity: float = 980.0\n'
        '\n'
        '@onready var player: CharacterBody2D = $Player\n'
        '\n'
        'func _ready() -> void:\n'
        f'\tprint("[main] {concept.display_title} ready")\n'
        '\n'
        'func _physics_process(delta: float) -> void:\n'
        '\tvar velocity := player.velocity\n'
        '\tvelocity.y += gravity * delta\n'
        '\tvar dir := Input.get_axis("ui_left", "ui_right")\n'
        '\tvelocity.x = dir * move_speed\n'
        '\tif Input.is_action_just_pressed("ui_up") and player.is_on_floor():\n'
        '\t\tvelocity.y = jump_velocity\n'
        '\tplayer.velocity = velocity\n'
        '\tplayer.move_and_slide()\n'
        '\n'
        '# TODO mechanics — fill in from the concept:\n'
        + "\n".join(f"#   - {m}" for m in (concept.mechanics or ["(none listed)"]))
    )
    return [("project.godot", "__main_scene__"),
            ("main.tscn", main_tscn),
            ("main.gd", main_gd)]


def _tpl_topdown(concept) -> List[Tuple[str, str]]:
    main_tscn = (
        '[gd_scene load_steps=2 format=3]\n'
        '\n'
        '[ext_resource type="Script" path="res://main.gd" id="1_main"]\n'
        '\n'
        '[node name="Main" type="Node2D"]\n'
        'script = ExtResource("1_main")\n'
        '\n'
        '[node name="Label" type="Label" parent="."]\n'
        'offset_left = 20.0\n'
        'offset_top = 20.0\n'
        'offset_right = 400.0\n'
        'offset_bottom = 80.0\n'
        f'text = "{concept.display_title}"\n'
        '\n'
        '[node name="Player" type="CharacterBody2D" parent="."]\n'
        'position = Vector2(400, 300)\n'
        '\n'
        '[node name="Sprite" type="ColorRect" parent="Player"]\n'
        'offset_left = -12.0\n'
        'offset_top = -12.0\n'
        'offset_right = 12.0\n'
        'offset_bottom = 12.0\n'
        'color = Color(0.83, 0.18, 0.18, 1)\n'
        '\n'
        '[node name="Collision" type="CollisionShape2D" parent="Player"]\n'
        '\n'
        '[node name="Camera" type="Camera2D" parent="Player"]\n'
    )
    main_gd = (
        '# main.gd — Top-down skeleton\n'
        f'# Concept: {concept.display_title}\n'
        f'# Genre:   {concept.genre or "Top-down"}\n'
        f'# Hook:    {concept.hook}\n'
        '\n'
        'extends Node2D\n'
        '\n'
        '@export var move_speed: float = 220.0\n'
        '\n'
        '@onready var player: CharacterBody2D = $Player\n'
        '\n'
        'func _ready() -> void:\n'
        f'\tprint("[main] {concept.display_title} ready")\n'
        '\n'
        'func _physics_process(_delta: float) -> void:\n'
        '\tvar input_vector := Vector2(\n'
        '\t\tInput.get_axis("ui_left", "ui_right"),\n'
        '\t\tInput.get_axis("ui_up", "ui_down"),\n'
        '\t)\n'
        '\tplayer.velocity = input_vector.normalized() * move_speed\n'
        '\tplayer.move_and_slide()\n'
        '\n'
        '# TODO mechanics — fill in from the concept:\n'
        + "\n".join(f"#   - {m}" for m in (concept.mechanics or ["(none listed)"]))
    )
    return [("project.godot", "__main_scene__"),
            ("main.tscn", main_tscn),
            ("main.gd", main_gd)]


def _tpl_puzzle(concept) -> List[Tuple[str, str]]:
    main_tscn = (
        '[gd_scene load_steps=2 format=3]\n'
        '\n'
        '[ext_resource type="Script" path="res://main.gd" id="1_main"]\n'
        '\n'
        '[node name="Main" type="Control"]\n'
        'anchors_preset = 15\n'
        'anchor_right = 1.0\n'
        'anchor_bottom = 1.0\n'
        'script = ExtResource("1_main")\n'
        '\n'
        '[node name="Title" type="Label" parent="."]\n'
        'offset_left = 20.0\n'
        'offset_top = 20.0\n'
        'offset_right = 800.0\n'
        'offset_bottom = 80.0\n'
        f'text = "{concept.display_title}"\n'
        '\n'
        '[node name="Board" type="GridContainer" parent="."]\n'
        'offset_left = 40.0\n'
        'offset_top = 100.0\n'
        'offset_right = 600.0\n'
        'offset_bottom = 600.0\n'
        'columns = 5\n'
    )
    main_gd = (
        '# main.gd — Puzzle skeleton\n'
        f'# Concept: {concept.display_title}\n'
        f'# Genre:   {concept.genre or "Puzzle"}\n'
        f'# Hook:    {concept.hook}\n'
        '\n'
        'extends Control\n'
        '\n'
        '@export var board_size: int = 5\n'
        '\n'
        '@onready var board: GridContainer = $Board\n'
        '\n'
        'func _ready() -> void:\n'
        f'\tprint("[main] {concept.display_title} ready")\n'
        '\tboard.columns = board_size\n'
        '\tfor i in board_size * board_size:\n'
        '\t\tvar cell := Button.new()\n'
        '\t\tcell.text = str(i + 1)\n'
        '\t\tcell.custom_minimum_size = Vector2(64, 64)\n'
        '\t\tcell.pressed.connect(_on_cell_pressed.bind(i))\n'
        '\t\tboard.add_child(cell)\n'
        '\n'
        'func _on_cell_pressed(idx: int) -> void:\n'
        '\tprint("[main] pressed cell %d" % idx)\n'
        '\n'
        '# TODO mechanics — fill in from the concept:\n'
        + "\n".join(f"#   - {m}" for m in (concept.mechanics or ["(none listed)"]))
    )
    return [("project.godot", "__main_scene__"),
            ("main.tscn", main_tscn),
            ("main.gd", main_gd)]


def _tpl_vn(concept) -> List[Tuple[str, str]]:
    main_tscn = (
        '[gd_scene load_steps=2 format=3]\n'
        '\n'
        '[ext_resource type="Script" path="res://main.gd" id="1_main"]\n'
        '\n'
        '[node name="Main" type="Control"]\n'
        'anchors_preset = 15\n'
        'anchor_right = 1.0\n'
        'anchor_bottom = 1.0\n'
        'script = ExtResource("1_main")\n'
        '\n'
        '[node name="Background" type="ColorRect" parent="."]\n'
        'anchor_right = 1.0\n'
        'anchor_bottom = 1.0\n'
        'color = Color(0.05, 0.05, 0.07, 1)\n'
        '\n'
        '[node name="Text" type="RichTextLabel" parent="."]\n'
        'anchor_left = 0.1\n'
        'anchor_right = 0.9\n'
        'anchor_top = 0.6\n'
        'anchor_bottom = 0.95\n'
        'bbcode_enabled = true\n'
        '\n'
        '[node name="Next" type="Button" parent="."]\n'
        'anchor_left = 0.45\n'
        'anchor_right = 0.55\n'
        'anchor_top = 0.96\n'
        'anchor_bottom = 1.0\n'
        'text = "Continue"\n'
    )
    lines = [
        concept.premise or concept.hook or "Press Continue to begin.",
        "(TODO: load the script from a data file.)",
        f"— Audience: {concept.target_audience}" if concept.target_audience else "",
    ]
    main_gd = (
        '# main.gd — Visual novel skeleton\n'
        f'# Concept: {concept.display_title}\n'
        f'# Genre:   {concept.genre or "Visual Novel"}\n'
        f'# Hook:    {concept.hook}\n'
        '\n'
        'extends Control\n'
        '\n'
        f'var lines := {[l for l in lines if l]!r}\n'
        'var idx := 0\n'
        '\n'
        '@onready var text_box: RichTextLabel = $Text\n'
        '@onready var next_btn: Button = $Next\n'
        '\n'
        'func _ready() -> void:\n'
        '\tnext_btn.pressed.connect(_advance)\n'
        '\t_advance()\n'
        '\n'
        'func _advance() -> void:\n'
        '\tif idx >= lines.size():\n'
        '\t\ttext_box.text = "[i]end[/i]"\n'
        '\t\tnext_btn.disabled = true\n'
        '\t\treturn\n'
        '\ttext_box.text = lines[idx]\n'
        '\tidx += 1\n'
    )
    return [("project.godot", "__main_scene__"),
            ("main.tscn", main_tscn),
            ("main.gd", main_gd)]


# Per-genre TODO suggestions stamped into the generic skeleton when we
# fall through (no dedicated template for this genre). The Coder agent
# uses these as concrete next-step hooks. Keep the lists short — the
# user is going to read all of them.
_GENERIC_TODOS_BY_GENRE: Dict[str, List[str]] = {
    "rhythm": [
        "load a beatmap (JSON: array of {time_ms, lane}) into _ready()",
        "spawn note nodes that travel a fixed lane over N seconds",
        "score press timing against a hit window (e.g. ±80ms perfect, ±150ms ok)",
    ],
    "deck builder": [
        "represent the player deck as Array[Resource] of Card",
        "draw N cards into the hand container per turn",
        "implement a single resolve-card-effect dispatcher",
    ],
    "racing": [
        "use VehicleBody3D or a simple kinematic 2D car body",
        "lap-counter via Area2D start-line trigger",
        "store best lap time in user://lap_records.json",
    ],
    "horror": [
        "first-person Camera3D in a Node3D rig (or Camera2D for 2D)",
        "stamina + flashlight battery as exported floats with timers",
        "an enemy AI Node with patrol / chase / lose-sight states",
    ],
    "stealth": [
        "guard FOV via raycasts in a SightCone Node2D",
        "alert level int exported per-guard; broadcast on detection",
        "noise events as signals routed through an Autoload",
    ],
    "sandbox": [
        "tile-grid world via TileMap with an inventory autoload",
        "place / break tile actions on left/right click",
        "save the world to a JSON in user://worlds/",
    ],
}


def _generic_todos_for(genre: str) -> List[str]:
    """Pick the right TODO bullet-list for a genre that didn't get a
    dedicated template. Falls back to a small "any game" list."""
    g = (genre or "").lower()
    for key, todos in _GENERIC_TODOS_BY_GENRE.items():
        if key in g:
            return todos
    return [
        "decide what the player does in 30 seconds, then in 5 minutes",
        "wire ONE input action that produces ONE visible effect",
        "add a Game Manager Autoload for shared state",
    ]


def _tpl_generic(concept) -> List[Tuple[str, str]]:
    # Stamp the detected genre into the script so:
    #   • The user sees it at the top of main.gd
    #   • The Coder agent has an unambiguous hook for "fill this in"
    # The TODOs below are genre-aware so even a "generic" scaffold
    # points the user toward the next concrete step rather than
    # leaving them at a blank Node2D.
    detected_genre = concept.genre or "(unspecified)"
    todos = _generic_todos_for(detected_genre)
    main_tscn = (
        '[gd_scene load_steps=2 format=3]\n'
        '\n'
        '[ext_resource type="Script" path="res://main.gd" id="1_main"]\n'
        '\n'
        '[node name="Main" type="Node2D"]\n'
        'script = ExtResource("1_main")\n'
        '\n'
        '[node name="Label" type="Label" parent="."]\n'
        'offset_left = 40.0\n'
        'offset_top = 40.0\n'
        'offset_right = 600.0\n'
        'offset_bottom = 100.0\n'
        f'text = "{concept.display_title}"\n'
    )
    main_gd_lines = [
        '# main.gd — Generic skeleton',
        f'# ANVIL_GENRE: {detected_genre}',
        f'# Concept: {concept.display_title}',
        f'# Hook:    {concept.hook}',
        '#',
        f'# Anvil does not yet ship a dedicated template for '
        f'{detected_genre!r}.',
        '# The TODO list below is a concrete starting point — ask the',
        '# Coder agent ("🤖 Ask Coder") to flesh out any one of these:',
    ]
    for t in todos:
        main_gd_lines.append(f"#   - {t}")
    main_gd_lines += [
        "",
        "extends Node2D",
        "",
        "func _ready() -> void:",
        f"\tprint(\"[main] {concept.display_title} ready\")",
    ]
    main_gd = "\n".join(main_gd_lines)
    return [("project.godot", "__main_scene__"),
            ("main.tscn", main_tscn),
            ("main.gd", main_gd)]


_TEMPLATES = {
    "platformer": _tpl_platformer,
    "topdown":    _tpl_topdown,
    "puzzle":     _tpl_puzzle,
    "vn":         _tpl_vn,
    "generic":    _tpl_generic,
}


# ============================================================
# README rendering
# ============================================================

def _render_readme(concept, template_name: str) -> str:
    def _section(title: str, body) -> str:
        if not body:
            return ""
        if isinstance(body, list):
            body = "\n".join(f"- {b}" for b in body if b)
        return f"## {title}\n\n{body}\n\n"

    parts = [
        f"# {concept.display_title}\n\n",
        f"_Generated by Anvil demo_builder from concept "
        f"`{concept.id}` on "
        f"{datetime.now().strftime('%Y-%m-%d')}._\n\n",
        f"**Template:** `{template_name}`\n",
        f"**Engine:** {concept.engine or 'Godot 4'}\n\n",
        _section("Hook", concept.hook),
        _section("Premise", concept.premise),
        _section("Core loop", concept.core_loop),
        _section("Mechanics", concept.mechanics),
        _section("Genre", concept.genre),
        _section("Sub-genres", concept.sub_genres),
        _section("Art style", concept.art_style),
        _section("Target audience", concept.target_audience),
        _section("Comparable titles", concept.comparable_titles),
        _section("What sets it apart", concept.differentiator),
        _section("Why it works", concept.why_it_works),
    ]
    # If we fell through to the generic template, surface the
    # genre-aware TODO list explicitly in the README so the user
    # knows what's NOT in the scaffold yet.
    if template_name == "generic":
        todos = _generic_todos_for(concept.genre or "")
        parts.append(
            "## Anvil notes\n\n"
            f"This scaffold uses the **generic** skeleton — Anvil does "
            f"not yet ship a dedicated template for "
            f"`{concept.genre or '(unspecified)'}`. The script just "
            f"prints a ready message and shows the title; the next "
            f"layer is up to you (or the Coder agent).\n\n"
            f"Concrete next steps for a `{concept.genre or 'game'}`:\n\n"
            + "\n".join(f"- {t}" for t in todos)
            + "\n\n"
            "Each one is a one-shot request for 🤖 Ask Coder. Pick "
            "the smallest and ship it before the next.\n\n"
        )
    parts += [
        "## Next steps\n\n",
        "- Open this folder in the Godot Workspace and hit ▶ Run.\n",
        "- Use 🤖 Ask Coder to flesh out one mechanic at a time.\n",
        "- The TODO list in `main.gd` mirrors the concept's mechanics.\n",
    ]
    return "".join(p for p in parts if p)


# ============================================================
# Slug helper
# ============================================================

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(s: str) -> str:
    base = _SLUG_RE.sub("_", (s or "").lower()).strip("_")
    return (base or "demo")[:48]


# ============================================================
# Public API
# ============================================================

def build_demo(
    concept: Any,
    vault_dir: Any,
    *,
    overwrite: bool = False,
) -> DemoBuildResult:
    """Generate a Godot 4 skeleton for ``concept`` under
    ``<vault_dir>/projects/<slug>/``.

    Returns ``DemoBuildResult``. On success, ``result.project_path``
    is the absolute path the user can open in Godot Workspace.
    On failure, ``result.error`` describes what went wrong.

    ``overwrite=False`` refuses to write into an existing non-empty
    project folder (returns an error). Caller is expected to confirm
    with the user before retrying with ``overwrite=True``.
    """
    if concept is None:
        return DemoBuildResult(error="no concept supplied")
    try:
        base = Path(vault_dir).expanduser().resolve() / "projects"
        base.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        return DemoBuildResult(error=f"could not create projects dir: {exc!r}")

    slug = _slugify(getattr(concept, "title", "") or getattr(concept, "id", "demo"))
    project_path = base / slug

    if project_path.exists() and any(project_path.iterdir()) and not overwrite:
        return DemoBuildResult(
            project_path=project_path,
            error=f"{project_path.name} already exists and is non-empty",
        )

    try:
        project_path.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        return DemoBuildResult(error=f"could not create project dir: {exc!r}")

    template_name = _pick_template(getattr(concept, "genre", "") or "")
    tpl = _TEMPLATES.get(template_name, _tpl_generic)
    pairs = tpl(concept)

    main_scene = "res://main.tscn"
    project_godot = _project_godot(
        concept_title=getattr(concept, "display_title",
                              getattr(concept, "title", "Demo")),
        main_scene=main_scene,
    )

    files_written: List[Path] = []
    notes: List[str] = []
    try:
        for rel, content in pairs:
            if content == "__main_scene__":
                # placeholder slot for project.godot — render it now
                rel = "project.godot"
                content = project_godot
            target = project_path / rel.replace("/", "/")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            files_written.append(target)
        # icon
        (project_path / "icon.svg").write_text(_ICON_SVG, encoding="utf-8")
        files_written.append(project_path / "icon.svg")
        # README
        readme_text = _render_readme(concept, template_name)
        (project_path / "README.md").write_text(readme_text, encoding="utf-8")
        files_written.append(project_path / "README.md")
    except Exception as exc:
        return DemoBuildResult(
            project_path=project_path,
            files_written=files_written,
            error=f"write failed: {exc!r}",
        )

    notes.append(f"Template selected: {template_name}")
    notes.append(f"Files written: {len(files_written)}")
    return DemoBuildResult(
        project_path=project_path,
        files_written=files_written,
        notes=notes,
    )
