"""
sim_harness_gen.py — generate a headless balance-sim harness for a
Godot game on request.

Anvil can already SWEEP a game that ships its own sim harness (the
``godot_csv`` backend reads ``[SIM]`` stdout + ``sim_results.csv``).
This module CREATES that harness for a game that doesn't have one —
closing the loop GDD → built game → **generated sim** → sweep →
analyze.

What it emits
------------
For a target game it writes two artifacts the existing backend ingests
verbatim, so no new runner code is needed:

  1. ``scripts/sim/Sim.gd`` — a self-contained ``extends SceneTree``
     harness. It instances the game's main scene headless, finds the
     player ``CharacterBody2D``, drives it with a small seeded AI
     (``move_and_slide`` itself — it does NOT depend on the game's
     ``_physics_process``, which is empty in dry-run builds), samples
     HP each sim-second, ends each run on death / cap, and writes the
     exact CSV + ``[SIM]`` lines ``godot_sim_runner_csv`` parses.

  2. ``sim_contracts/<slug>.sim.json`` — a ``SimContract`` (loadable
     via ``godot_sim_project.load_contract``) whose sweepable knobs
     are ``const``s INSIDE the generated harness (MOVE_SPEED,
     CONTACT_BAND, ENGAGE_BAND), so ``GdConstPatcher`` can sweep them
     with zero new patch machinery.

No AI art, ever
---------------
The generator touches only GDScript + a JSON contract. It never
creates, imports, or requests image/audio assets. Visuals in the
generated game stay ColorRect/Label placeholders the user hand-paints
in the Pixel Art tab.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from godot_sim_project import KnobTarget, SimContract


# The canonical 17-column CSV header the godot_csv backend expects.
# A generic GDD game only meaningfully fills survived_s / died /
# victory / kills; the rest are written as 0 to keep the schema valid.
CSV_COLUMNS = [
    "char", "strategy", "seed", "died", "survived_s", "victory",
    "kills", "level", "dmg_dealt", "dmg_taken", "dps", "chests",
    "min_hp", "t_chieftain1", "t_lord", "t_chieftain2", "t_king",
]


# ============================================================
# Harness spec
# ============================================================

@dataclass
class HarnessSpec:
    """Everything the GDScript template needs to target a game.

    Derived from a ``gdd_planner.Plan`` via ``spec_from_plan`` or
    hand-built for an arbitrary project (probe mode).
    """
    title:        str = "game"
    scene_path:   str = "res://main.tscn"   # the main scene to instance
    player_node:  str = "Player"            # node name to drive
    move_style:   str = "topdown"           # "topdown" | "platformer"
    hp_autoload:  str = "GameManager"       # autoload exposing hp/score/victory
    enemies_node: str = "Enemies"           # scene folder of enemy nodes
    move_speed:   float = 220.0
    contact_band: float = 64.0
    engage_band:  float = 160.0
    default_cap:  float = 60.0
    # Per-entity @export tunables to expose as sweep knobs:
    #   {"game.<slug>.<var>": (relative_script_path, var_name)}
    value_exports: Dict[str, tuple] = field(default_factory=dict)
    notes:        List[str] = field(default_factory=list)


# ============================================================
# GDScript template
# ============================================================

# Sentinel tokens (NOT str.format — GDScript is brace-heavy). Each
# __TOKEN__ is .replace()'d by render_sim_harness.
_SIM_TEMPLATE = r'''extends SceneTree

# ============================================================
# AUTO-GENERATED by Anvil (sim_harness_gen.py) — DO NOT hand-edit;
# regenerate from the game's plan instead.
#
# Headless balance-sim harness for "__TITLE__". Drives the player with
# a small seeded AI, runs a char x strategy x seed matrix, and writes
# sim_results.csv + [SIM] stdout that Anvil's godot_csv backend reads.
#
# Run (Anvil does this for you on a throwaway COPY):
#   godot --headless --fixed-fps 30 -s res://scripts/sim/Sim.gd -- \
#       seeds=1 cap=60 fps=30 chars=player strategies=default
#
# OUT_DIR is rewritten by Anvil to point into the working copy, so the
# original project is never modified.
# ============================================================

# --- Output redirect (Anvil rewrites this const) ---
const OUT_DIR := "__OUT_DIR__"

# --- Target wiring (filled by the generator) ---
const SCENE_PATH := "__SCENE_PATH__"
const PLAYER_NODE := "__PLAYER_NODE__"
const MOVE_STYLE := "__MOVE_STYLE__"        # "topdown" | "platformer"
const HP_AUTOLOAD := "__HP_AUTOLOAD__"
const ENEMIES_NODE := "__ENEMIES_NODE__"    # scene node holding enemies

# --- Sweepable knobs (Anvil's GdConstPatcher patches these) ---
const MOVE_SPEED := __MOVE_SPEED__          # AI player move speed (px/s)
const CONTACT_BAND := __CONTACT_BAND__      # flee enemies closer than this
const ENGAGE_BAND := __ENGAGE_BAND__        # seek toward enemies within this

var fps: int = 30
var cap: float = __DEFAULT_CAP__
var chars: Array = ["player"]
var strategies: Array = ["default"]
var seeds: int = 1

var _queue: Array = []
var _inst = null
var _cfg: Dictionary = {}
var _csv: FileAccess = null
var _results: Array = []
var _started: int = 0
var _elapsed: float = 0.0
var _min_hp: float = 1.0e9
var _kills: int = 0
var _heading: Vector2 = Vector2.RIGHT
var _prev_enemy_count: int = 0
var _rng := RandomNumberGenerator.new()
var _grace: float = 0.0


func _initialize() -> void:
	_parse_args()
	Engine.physics_ticks_per_second = fps
	Engine.max_fps = 0
	for c in chars:
		for s in strategies:
			for i in range(seeds):
				_queue.append({"char": c, "strategy": s, "seed": 1000 + i})
	_csv = FileAccess.open(OUT_DIR + "sim_results.csv", FileAccess.WRITE)
	if _csv != null:
		_csv.store_line("char,strategy,seed,died,survived_s,victory,kills,level,dmg_dealt,dmg_taken,dps,chests,min_hp,t_chieftain1,t_lord,t_chieftain2,t_king")
		_csv.flush()
	print("[SIM] config: chars=", chars, " strategies=", strategies, " seeds=", seeds, " cap=", cap, "s fps=", fps, " -> ", _queue.size(), " runs")


func _parse_args() -> void:
	for a in OS.get_cmdline_user_args():
		var kv := String(a).split("=")
		if kv.size() != 2:
			continue
		match kv[0]:
			"seeds": seeds = int(kv[1])
			"cap": cap = float(kv[1])
			"fps": fps = int(kv[1])
			"chars": chars = kv[1].split(",")
			"strategies": strategies = kv[1].split(",")


func _process(delta: float) -> bool:
	if _inst == null:
		if _queue.is_empty():
			_finalize()
			return true
		_begin_run(_queue.pop_front())
		return false
	# Active run.
	_elapsed += delta
	_grace += delta
	_drive_player(delta)
	_min_hp = minf(_min_hp, _player_hp())
	# A short grace period stops a run ending on tick 0 before the
	# scene has initialised its HP.
	if _grace > 0.5 and (_is_dead() or _is_victory()) or _elapsed >= cap:
		_end_run()
	return false


# ----------------------------------------------------------------- run control
func _begin_run(cfg: Dictionary) -> void:
	_cfg = cfg
	_elapsed = 0.0
	_grace = 0.0
	_min_hp = 1.0e9
	_kills = 0
	_prev_enemy_count = 0
	_rng.seed = int(cfg["seed"])
	seed(int(cfg["seed"]))
	_heading = Vector2.RIGHT.rotated(_rng.randf() * TAU)
	var packed := load(SCENE_PATH) as PackedScene
	if packed == null:
		push_error("[SIM] could not load scene: " + SCENE_PATH)
		_finalize()
		return
	_inst = packed.instantiate()
	get_root().add_child(_inst)
	_started += 1


func _end_run() -> void:
	var survived := _elapsed
	var died := _is_dead()
	var victory := _is_victory()
	var level := _read_num(["level"], 0.0)
	var rec := {
		"char": _cfg["char"], "strategy": _cfg["strategy"], "seed": _cfg["seed"],
		"died": died, "survived": survived, "victory": victory,
		"kills": _kills, "level": int(level),
		"min_hp": (0.0 if _min_hp > 1.0e8 else _min_hp),
	}
	_results.append(rec)
	_append_csv_row(rec)
	var dps := 0.0
	print("[SIM] %d/%d  %s/%s seed=%d  survived=%.0fs died=%s victory=%s kills=%d lvl=%d dps=%.0f" % [
		_results.size(), _started + _queue.size(),
		str(rec["char"]), str(rec["strategy"]), int(rec["seed"]),
		survived, str(died), str(victory), _kills, int(level), dps])
	if is_instance_valid(_inst):
		_inst.queue_free()
	_inst = null


# ----------------------------------------------------------------- AI brain
func _player():
	if _inst == null or not is_instance_valid(_inst):
		return null
	if _inst.name == PLAYER_NODE:
		return _inst
	return _inst.find_child(PLAYER_NODE, true, false)


func _enemies() -> Array:
	var out: Array = []
	if _inst == null or not is_instance_valid(_inst):
		return out
	var folder = _inst.find_child(ENEMIES_NODE, true, false)
	if folder != null:
		for c in folder.get_children():
			if c is Node2D and is_instance_valid(c):
				out.append(c)
	return out


func _drive_player(delta: float) -> void:
	var p = _player()
	if p == null or not is_instance_valid(p) or not (p is CharacterBody2D):
		return
	var ppos: Vector2 = p.global_position
	# Kill count: enemies that vanished since last tick (a real game's
	# combat removes them). Lets the sim score offense, not just survival.
	var enemies := _enemies()
	if enemies.size() < _prev_enemy_count:
		_kills += _prev_enemy_count - enemies.size()
	_prev_enemy_count = enemies.size()
	# Nearest enemy drives flee/seek through CONTACT_BAND / ENGAGE_BAND —
	# the persona-tuned bands Anvil patches per run, so Cautious kites
	# from farther and Aggressive hugs the pack.
	var nearest = null
	var nd := 1.0e9
	for e in enemies:
		var d: float = ppos.distance_to(e.global_position)
		if d < nd:
			nd = d
			nearest = e
	var desired := Vector2.ZERO
	if nearest != null and nd < CONTACT_BAND:
		desired = (ppos - nearest.global_position).normalized()        # flee
	elif nearest != null and nd > ENGAGE_BAND:
		desired = (nearest.global_position - ppos).normalized()        # close in
	else:
		if _rng.randf() < 0.03:
			_heading = _heading.rotated(_rng.randf_range(-1.2, 1.2))
		desired = _heading
	# Steer back from the arena edge so the player doesn't pin a wall.
	if ppos.length() > 1200.0:
		desired = (desired + (-ppos).normalized()).normalized()
	if MOVE_STYLE == "platformer":
		p.velocity.x = desired.x * MOVE_SPEED
		if not p.is_on_floor():
			p.velocity.y += 980.0 * delta
		elif desired.y < -0.3 or _rng.randf() < 0.04:
			p.velocity.y = -400.0
	else:
		p.velocity = desired * MOVE_SPEED
	p.move_and_slide()


# ----------------------------------------------------------------- state reads
func _hp_node():
	# Autoloads live under /root in -s mode IF Godot registered them.
	# Fall back to the instanced scene root (some games keep hp there).
	var gm = get_root().get_node_or_null(HP_AUTOLOAD)
	if gm != null:
		return gm
	if _inst != null and is_instance_valid(_inst):
		return _inst
	return null


func _read_num(keys: Array, default: float) -> float:
	var src = _hp_node()
	if src == null:
		return default
	for k in keys:
		var v = src.get(k)
		if v != null and (typeof(v) == TYPE_INT or typeof(v) == TYPE_FLOAT):
			return float(v)
	return default


func _player_hp() -> float:
	return _read_num(["hp", "health", "player_hp"], 100.0)


func _is_dead() -> bool:
	if _player_hp() <= 0.0:
		return true
	var src = _hp_node()
	if src != null:
		var go = src.get("game_over")
		if typeof(go) == TYPE_BOOL and go:
			return true
	# Player node despawned entirely.
	var p = _player()
	return p == null


func _is_victory() -> bool:
	var src = _hp_node()
	if src != null:
		for k in ["victory", "won", "win"]:
			var v = src.get(k)
			if typeof(v) == TYPE_BOOL and v:
				return true
	return false


# ----------------------------------------------------------------- reporting
func _finalize() -> void:
	if _csv != null:
		_csv.close()
	print("[SIM] DONE - ", _results.size(), " runs. Wrote sim_results.csv")


func _append_csv_row(r: Dictionary) -> void:
	if _csv == null:
		return
	# Order matches the header. dmg/dps/chests/boss-times are 0/-1 for a
	# generic game (no combat economy); died/victory are lowercase.
	_csv.store_line("%s,%s,%d,%s,%.1f,%s,%d,%d,%.0f,%.0f,%.1f,%d,%.0f,%.1f,%.1f,%.1f,%.1f" % [
		str(r["char"]), str(r["strategy"]), int(r["seed"]),
		str(r["died"]).to_lower(), float(r["survived"]),
		str(r["victory"]).to_lower(), int(r["kills"]), int(r["level"]),
		0.0, 0.0, 0.0, 0, float(r["min_hp"]),
		-1.0, -1.0, -1.0, -1.0])
	_csv.flush()
'''


def render_sim_harness(spec: HarnessSpec) -> str:
    """Render the Sim.gd source for ``spec``."""
    out = _SIM_TEMPLATE
    repl = {
        "__TITLE__": spec.title.replace("\n", " "),
        "__OUT_DIR__": "",   # Anvil rewrites this before each run
        "__SCENE_PATH__": spec.scene_path,
        "__PLAYER_NODE__": spec.player_node,
        "__MOVE_STYLE__": spec.move_style,
        "__HP_AUTOLOAD__": spec.hp_autoload,
        "__ENEMIES_NODE__": spec.enemies_node,
        "__MOVE_SPEED__": _fmt_float(spec.move_speed),
        "__CONTACT_BAND__": _fmt_float(spec.contact_band),
        "__ENGAGE_BAND__": _fmt_float(spec.engage_band),
        "__DEFAULT_CAP__": _fmt_float(spec.default_cap),
    }
    for k, v in repl.items():
        out = out.replace(k, v)
    return out


def _fmt_float(v: Any) -> str:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return "0.0"
    # Always keep a decimal so GDScript infers float (avoids int/float
    # division surprises and keeps the GdConstPatcher anchor a float).
    if f.is_integer():
        return f"{f:.1f}"
    return repr(round(f, 4))


# ============================================================
# Plan → spec / contract
# ============================================================

def spec_from_plan(plan: Any) -> HarnessSpec:
    """Derive a HarnessSpec from a ``gdd_planner.Plan``.

    Player node name = the player entity's first word (matches
    ``gdd_planner._inline_entity_node``). Move style from the genre
    template. Move speed from the player's exported ``move_speed`` if
    present, else a genre default.
    """
    title = getattr(plan, "title", "") or "game"
    template = (getattr(plan, "template", "") or "generic").lower()
    move_style = "platformer" if template == "platformer" else "topdown"

    # Find the player entity + its first-word node name.
    player_node = "Player"
    move_speed = 220.0
    registry = getattr(plan, "entity_registry", {}) or {}
    for slug, ent in registry.items():
        role = getattr(ent, "role", "")
        if role == "player":
            nm = (getattr(ent, "name", "") or "Player").split()
            if nm:
                player_node = nm[0]
            break

    # Walk every script's exported tunables: pull the player's
    # move_speed for the harness default, and register all numeric
    # @export vars (player move/jump, enemy hp/speed/damage, item value)
    # as sweepable game-VALUE knobs keyed by "game.<slug>.<var>".
    value_exports: Dict[str, tuple] = {}
    for sp in getattr(plan, "scripts", []) or []:
        slug = getattr(sp, "entity", None)
        role = getattr(registry.get(slug), "role", "") if slug else ""
        rel = getattr(sp, "file", "") or ""
        for (vname, vtype, vdefault) in getattr(sp, "exported_vars", []) or []:
            if vtype not in ("int", "float"):
                continue
            if role == "player" and vname == "move_speed":
                try:
                    move_speed = float(vdefault)
                except (TypeError, ValueError):
                    pass
            if rel and slug:
                value_exports[f"game.{slug}.{vname}"] = (rel, vname)

    return HarnessSpec(
        title=title,
        scene_path="res://main.tscn",
        player_node=player_node,
        move_style=move_style,
        hp_autoload="GameManager",
        enemies_node="Enemies",
        move_speed=move_speed,
        default_cap=60.0,
        value_exports=value_exports,
    )


def build_sim_contract(spec: HarnessSpec) -> SimContract:
    """Build a SimContract for a generated game.

    BEHAVIOR knobs are consts inside the generated Sim.gd (MOVE_SPEED +
    the AI bands), patched with ``set_const``. VALUE knobs are the
    game's own ``@export var`` tunables (enemy hp/speed/damage, player
    jump), patched in their per-entity scripts with ``set_export_var``
    — so a generated game sweeps both how the AI plays AND the game's
    balance numbers.
    """
    brain = "scripts/sim/Sim.gd"
    brain_knobs = {
        "brain.MOVE_SPEED":   KnobTarget("brain", "const", name="MOVE_SPEED"),
        "brain.CONTACT_BAND": KnobTarget("brain", "const", name="CONTACT_BAND"),
        "brain.ENGAGE_BAND":  KnobTarget("brain", "const", name="ENGAGE_BAND"),
    }
    value_knobs = {}
    for key, (rel_path, var_name) in (spec.value_exports or {}).items():
        # file = the entity's own script (resolve_file passes it through);
        # kind 'export' patches the @export var line.
        value_knobs[key] = KnobTarget(rel_path, "export", name=var_name)
    return SimContract(
        name=_slug(spec.title),
        sim_script="res://scripts/sim/Sim.gd",
        fixed_fps=30,
        cap=spec.default_cap,
        seeds_per_cell=1,
        balance_file=brain,        # same file; no separate Balance.gd
        brain_file=brain,
        out_dir_const="OUT_DIR",
        csv_name="sim_results.csv",
        csv_columns=list(CSV_COLUMNS),
        char_arg="chars",
        strategy_arg="strategies",
        char_default="player",
        strategy_default="default",
        value_knobs=value_knobs,
        brain_knobs=brain_knobs,
    )


def contract_to_dict(contract: SimContract) -> Dict[str, Any]:
    """Serialize a SimContract to the dict shape ``load_contract`` /
    ``_contract_from_json`` reads back."""
    def _knobs(d: Dict[str, KnobTarget]) -> Dict[str, Any]:
        return {
            k: {"file": kt.file, "kind": kt.kind, "name": kt.name,
                "path": list(kt.path), "regex": kt.regex}
            for k, kt in d.items()
        }
    return {
        "name": contract.name,
        "sim_script": contract.sim_script,
        "fixed_fps": contract.fixed_fps,
        "cap": contract.cap,
        "seeds_per_cell": contract.seeds_per_cell,
        "balance_file": contract.balance_file,
        "brain_file": contract.brain_file,
        "out_dir_const": contract.out_dir_const,
        "csv_name": contract.csv_name,
        "csv_columns": list(contract.csv_columns),
        "char_arg": contract.char_arg,
        "strategy_arg": contract.strategy_arg,
        "char_default": contract.char_default,
        "strategy_default": contract.strategy_default,
        "value_knobs": _knobs(contract.value_knobs),
        "brain_knobs": _knobs(contract.brain_knobs),
    }


def write_sim_contract_json(contract: SimContract, path: Any) -> Path:
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        json.dumps(contract_to_dict(contract), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return p


# ============================================================
# One-call generation for a built project
# ============================================================

def generate_for_project(
    plan: Any,
    project_path: Any,
    *,
    spec: Optional[HarnessSpec] = None,
) -> Tuple[Path, Path]:
    """Write ``scripts/sim/Sim.gd`` + ``sim_contracts/<slug>.sim.json``
    into ``project_path``. Returns ``(sim_gd_path, contract_path)``.

    Safe to call in dry-run builds — it only writes GDScript + JSON.
    """
    project_path = Path(project_path)
    spec = spec or spec_from_plan(plan)
    contract = build_sim_contract(spec)

    sim_dir = project_path / "scripts" / "sim"
    sim_dir.mkdir(parents=True, exist_ok=True)
    sim_gd = sim_dir / "Sim.gd"
    sim_gd.write_text(render_sim_harness(spec), encoding="utf-8")

    contract_path = project_path / "sim_contracts" / f"{contract.name}.sim.json"
    write_sim_contract_json(contract, contract_path)
    return sim_gd, contract_path


# ============================================================
# Helpers
# ============================================================

_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slug(text: str) -> str:
    s = _SLUG_RE.sub("_", (text or "game").lower()).strip("_")
    return (s or "game")[:40]
