"""
Ready-made Qt wireframes, each built as a real Qt project and opened.

WHY THESE EXIST
---------------
Until now the Qt target was proven on ONE wireframe: test_gui_qt_runtime.py
drives image_viewer, and test_gui_emit_qt_kinds.py builds one or two shapes at
a time. Every defect the Qt emitter fix just closed lived in the space between
those — a combination nobody had drawn:

  * a window whose only shape is a frame, or a container holding exactly one
    widget, died in MainUi._build with "QGridLayout.addLayout(): not enough
    arguments" (gui_layout packs a sole child; the emitter spelled pack with a
    box-layout overload QGridLayout does not have)
  * a menubar whose menus were a list of titles killed emit itself with
    "'str' object has no attribute 'get'"
  * ANY window with a radiobutton died inside Ports(self), because _RadioPort
    set an attribute its __slots__ did not name

None of those needs an unusual wireframe. A login form, a tabbed settings
dialog, a split browser — the first things anyone draws — each walked into one.
So this suite is a shelf of ordinary wireframes, in tiers, and every one goes
through the WHOLE path a user's does: the .gspec on disk -> a Qt project in a
vault -> council_core.designer_project.generate (the Designer's own Generate)
-> the policy gate -> every file compiles -> App() constructed offscreen and
shown.

THE TIERS
---------
  a_*  kinds the Qt runtime is already proven on (labels, entries, buttons, a
       listbox, and the image viewer's folder -> scrubber -> canvas link)
  b_*  what the emitter fix made work: toolbar, status bar, splitters, tabs,
       group boxes, radio groups, nested and single-child containers
  c_*  edges the Qt target degrades on by design — a menubar spelled two ways,
       a fractional scale QSlider cannot hold, colour on kinds that cannot
       take it. Each must still build; where the degradation is deliberate,
       the probe checks it degrades the way the generated code says it does.

The tier is the file-name prefix, so it is visible in a folder listing and
cannot drift from a table kept somewhere else.

WHY THE .gspec FILES ARE GENERATED BY CODE IN THIS FILE
-------------------------------------------------------
A hand-typed wireframe is where a 4 px overlap, a child 2 px outside its frame
or a notebook with three pages and two tab titles comes from — and each of
those makes layout inference fall back or re-parent, so the case would test
the fallback instead of the widget. The builders below place every shape on
the 8 px grid, inside its container with a 16 px margin, containers first; the
rule check then re-proves that from the file on disk, and a drift test fails if
the file and its builder ever disagree. To change a case, edit its builder and
rewrite the files:

    python -m tests.test_qt_wireframes --write

WHY A SUBFOLDER
---------------
gui_examples.names() globs examples/gui/*.gspec NON-recursively, and whatever
it returns can be fed to a designing model as a worked example. These are test
fixtures, several deliberately degraded, and teaching a model from a menubar
spelled as a bare list of strings would be teaching it the edge case. One test
below pins that they stay out.
"""
from __future__ import annotations

import json
import os
import re
import sys
import time
import uuid
from collections import defaultdict
from contextlib import contextmanager
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Before PySide6 is imported by anything. A "windows"-platform QApplication
# flips the process to per-monitor DPI awareness and shrinks an already-open
# Tk window ~20% (measured; see test_gui_qt_runtime.py), which would corrupt
# the session-scoped Tk fixture other files in the same run depend on.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
# A handler that reports a failure opens a modal QMessageBox otherwise, and an
# unattended run waits forever for the click (the runtime suite hung on
# exactly that before the switch existed).
os.environ.setdefault("COUNCIL_NO_DIALOGS", "1")

import gui_policy  # noqa: E402
import gui_projects  # noqa: E402
from gui_shapes import (GENERIC_KIND, PALETTE, Canvas, Project,  # noqa: E402
                        Shape, Window, is_container, load_gspec, new_shape,
                        required_version, save_gspec)
from gui_spec import COMMAND_KINDS  # noqa: E402

CASES_DIR = ROOT / "examples" / "gui" / "qt_tests"
README = CASES_DIR / "README.md"

#: The Designer's canvas is fixed at 1100x700 (designer_project.CANVAS_W/H).
#: Layout inference measures edge-anchoring against the canvas size, so a case
#: drawn for any other canvas would infer anchors for one nobody drags on.
CANVAS_W, CANVAS_H, GRID = 1100, 700, 8

#: How far inside its container a child must sit. Containment is decided
#: geometrically with a few px of tolerance; 16 keeps every child unambiguously
#: inside, so a case never tests the re-parenting fallback by accident.
MARGIN = 16

_PROJECT_NAME = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _.-]{0,63}$")
_HEX = re.compile(r"^#[0-9a-fA-F]{6}$")


# ============================================================
# The builder
# ============================================================

def _shape_id(stem: str, index: int) -> str:
    """A stable id for shape ``index`` of case ``stem``.

    new_shape gives a fresh uuid4 every call, so two runs of the same builder
    would write two different files and the drift test could never pass.
    uuid5 is just as unique across cases and the same on every run."""
    return uuid.uuid5(uuid.NAMESPACE_URL,
                      f"council:examples/gui/qt_tests/{stem}#{index}").hex


class _Draw:
    """One wireframe, drawn shape by shape in the order a user would: every
    container before the things inside it. z is the drawing order, which is
    what containment inference and the tab order both read."""

    def __init__(self, stem: str, project: str, title: str) -> None:
        self.stem = stem
        self.project = Project(
            project=project, mode="linked",
            canvas=Canvas(w=CANVAS_W, h=CANVAS_H, grid_snap=GRID),
            window=Window(title=title))

    def __call__(self, kind: str, x: int, y: int, w: int, h: int,
                 label: str = "", *, port=None, drives=None, bg: str = "",
                 fg: str = "", **props) -> Shape:
        s = new_shape(kind, x, y, w=w, h=h, label=label)
        s.props.update(props)
        s.port = {"name": port} if isinstance(port, str) else dict(port or {})
        s.drives = dict(drives or {})
        s.bg, s.fg = bg, fg
        index = len(self.project.shapes)
        s.id = _shape_id(self.stem, index)
        s.z = index + 1
        self.project.shapes.append(s)
        return s


BUILDERS: Dict[str, Callable[[], Project]] = {}


def _case(stem: str, project: str, title: str):
    """Register a builder: ``stem`` is the file name (its prefix the tier),
    ``project`` the name the Designer would show, ``title`` the window's."""
    def register(fn: Callable[[_Draw], None]) -> Callable[[], Project]:
        def build() -> Project:
            draw = _Draw(stem, project, title)
            fn(draw)
            return draw.project
        BUILDERS[stem] = build
        return build
    return register


# Tier A — kinds the Qt runtime is already proven on.

@_case("a_login_form", "Login Form", "Sign in")
def _login_form(d: _Draw) -> None:
    d("label", 384, 192, 160, 24, "Username")
    d("entry", 384, 224, 336, 32, port="user_name")
    d("label", 384, 272, 160, 24, "Password")
    d("entry", 384, 304, 336, 32, port="password", show="*")
    d("button", 384, 360, 160, 32, "Sign in")
    d("label", 384, 416, 336, 24, port="message")


@_case("a_image_viewer", "Image Viewer", "Image Viewer")
def _image_viewer(d: _Draw) -> None:
    d("label", 24, 24, 160, 24, "Folder")
    d("file_picker", 24, 56, 520, 32, port="folder", mode="folder")
    d("image_canvas", 24, 112, 1048, 472, port="view")
    d("scrubber", 24, 608, 720, 40, "Frame", port="frame",
      drives={"folder": "folder", "target": "view",
              "current": "current_file", "status": "status"})
    d("label", 768, 616, 304, 24, port="current_file")
    d("status_bar", 0, 672, 1096, 24, port="status")


@_case("a_list_editor", "List Editor", "List Editor")
def _list_editor(d: _Draw) -> None:
    d("label", 24, 24, 160, 24, "Items")
    d("listbox", 24, 56, 480, 560, port="items")
    d("entry", 528, 56, 320, 32, port="new_item")
    d("button", 528, 104, 160, 32, "Add")
    # "Remove" is a name the policy gate denies as an attribute; gui_ports
    # derives remove_button for it. A real label, so it belongs in a real case.
    d("button", 528, 152, 160, 32, "Remove")
    d("button", 528, 200, 160, 32, "Clear all")


# Tier B — what the emitter fix made work.

@_case("b_toolbar_editor", "Text Editor", "Text Editor")
def _toolbar_editor(d: _Draw) -> None:
    d("toolbar", 0, 0, 1096, 40, "Main tools", buttons=["New", "Open", "Save"])
    d("text", 0, 48, 1096, 608, port="body")
    d("status_bar", 0, 664, 1096, 24, port="status")


@_case("b_split_browser", "Split Browser", "Split Browser")
def _split_browser(d: _Draw) -> None:
    d("label", 24, 16, 240, 24, "Library")
    d("panedwindow", 24, 48, 1048, 624, "Split")
    d("listbox", 48, 72, 304, 576, port="folders")
    d("treeview", 376, 72, 672, 576, port="files",
      columns=["Name", "Size", "Modified"])


@_case("b_options_group", "Options Panel", "Options")
def _options_group(d: _Draw) -> None:
    d("labelframe", 24, 24, 480, 400, "Output size")
    d("radiobutton", 48, 64, 200, 24, "Small", group="size", value="small")
    d("radiobutton", 48, 104, 200, 24, "Medium", group="size", value="medium")
    d("radiobutton", 48, 144, 200, 24, "Large", group="size", value="large")
    d("checkbutton", 48, 200, 240, 24, "Keep aspect ratio")
    d("checkbutton", 48, 240, 240, 24, "Sharpen")
    d("progressbar", 48, 296, 400, 24, port="progress")
    d("button", 24, 448, 160, 32, "Resize")


@_case("b_notebook_tabs", "Tabbed Settings", "Settings")
def _notebook_tabs(d: _Draw) -> None:
    # The pages are drawn SIDE BY SIDE inside the notebook — that is how a
    # wireframe says "three tabs" — and become tabs in drawing order.
    d("notebook", 24, 24, 1048, 560, "Sections",
      tabs=["General", "Display", "Advanced"])
    d("frame", 48, 64, 320, 496, "General page")
    d("frame", 392, 64, 320, 496, "Display page")
    d("frame", 736, 64, 320, 496, "Advanced page")
    d("label", 72, 88, 240, 24, "Name")
    d("entry", 72, 120, 272, 32, port="user_name")
    d("checkbutton", 416, 88, 240, 24, "Dark mode")
    d("combobox", 416, 128, 240, 32, port="text_size",
      values=["Small", "Medium", "Large"])
    d("spinbox", 760, 88, 160, 32, port="threads", from_=1, to=16)
    d("button", 760, 144, 160, 32, "Reset")
    d("button", 24, 608, 160, 32, "Save settings")


@_case("b_paned_vertical", "Console Split", "Console")
def _paned_vertical(d: _Draw) -> None:
    d("panedwindow", 24, 24, 1048, 592, "Console", orient="vertical")
    d("text", 48, 48, 1000, 352, port="script")
    d("log_pane", 48, 424, 1000, 168, port="output")
    d("button", 24, 640, 160, 32, "Run")


@_case("b_settings_form", "Settings Form", "Preferences")
def _settings_form(d: _Draw) -> None:
    d("label", 24, 32, 200, 24, "Theme")
    d("combobox", 240, 24, 240, 32, port="theme",
      values=["Light", "Dark", "System"])
    d("label", 24, 80, 200, 24, "Worker threads")
    d("spinbox", 240, 72, 240, 32, port="threads", from_=1, to=32)
    d("label", 24, 128, 200, 24, "Quality")
    d("scale", 240, 120, 240, 32, port="quality", from_=0, to=100)
    d("label", 24, 176, 200, 24, "Cache size (MB)")
    d("spinbox", 240, 168, 240, 32, port="cache_mb", from_=64, to=4096,
      increment=64)
    d("button", 240, 232, 160, 32, "Apply")


@_case("b_dashboard", "Dashboard", "Dashboard")
def _dashboard(d: _Draw) -> None:
    # `requires` makes this the one v3 case: the declared package travels
    # through generate into the policy gate as the project's own allowlist.
    d.project.requires = ["matplotlib"]
    d("label", 24, 16, 240, 24, "Throughput")
    d("chart_panel", 24, 48, 696, 424, port="chart")
    d("button", 744, 48, 160, 32, "Refresh")
    d("checkbutton", 744, 96, 200, 24, "Live updates")
    d("log_pane", 24, 496, 1048, 176, port="events")


@_case("b_nested_containers", "Nested Panels", "Copy Files")
def _nested_containers(d: _Draw) -> None:
    d("frame", 24, 24, 1048, 648, "Outer", relief="groove")
    d("labelframe", 48, 48, 488, 600, "Source")
    d("labelframe", 560, 48, 488, 600, "Target")
    d("label", 72, 80, 160, 24, "Source path")
    d("entry", 72, 112, 440, 32, port="source_path")
    d("listbox", 72, 160, 440, 464, port="source_files")
    d("label", 584, 80, 160, 24, "Target path")
    d("entry", 584, 112, 440, 32, port="target_path")
    d("button", 584, 160, 160, 32, "Copy")
    d("progressbar", 584, 208, 440, 24, port="copy_progress")


@_case("b_single_child_containers", "Single Child", "Single Child")
def _single_child_containers(d: _Draw) -> None:
    # One of each container kind that packs a sole child through a grid
    # layout — the exact emission that died with "QGridLayout.addLayout():
    # not enough arguments".
    d("frame", 24, 24, 336, 560, "Preview", relief="sunken")
    d("labelframe", 384, 24, 336, 560, "Notes")
    d("freeform", 744, 24, 328, 560, "Scratch")
    d("image_canvas", 48, 48, 288, 512, port="preview")
    d("text", 408, 56, 288, 504, port="notes")
    d("button", 768, 48, 160, 32, "Stamp")
    d("button", 24, 608, 160, 32, "Done")


@_case("b_single_root_shape", "Single Shape", "Picture")
def _single_root_shape(d: _Draw) -> None:
    d("image_canvas", 24, 24, 1048, 648, port="picture")


# Tier C — known degraded or edge behaviour.

@_case("c_menubar_dicts", "Menu Dicts", "Menus")
def _menubar_dicts(d: _Draw) -> None:
    d("menubar", 0, 0, 1096, 24, menus=[
        {"title": "File", "items": ["New", "Open", "-", "Quit"]},
        {"title": "Edit", "items": ["Undo", {"title": "Transform",
                                             "items": ["Upper case",
                                                       "Lower case"]}]},
        {"title": "Help", "items": ["About"]},
    ])
    d("text", 24, 48, 1048, 624, port="document")


@_case("c_menubar_titles", "Menu Titles", "Menus")
def _menubar_titles(d: _Draw) -> None:
    # A bare list of titles: what the designer's canvas draws happily, and what
    # killed emit with "'str' object has no attribute 'get'".
    d("menubar", 0, 0, 1096, 24, menus=["File", "View", "Help"])
    d("label", 24, 48, 480, 24, "These menus have no items yet")
    d("button", 24, 88, 160, 32, "Go")


@_case("c_float_scale", "Float Scale", "Exposure")
def _float_scale(d: _Draw) -> None:
    # QSlider holds whole numbers; Tk's Scale takes fractions. This case bends
    # the whole-number rule ON PURPOSE (see BENDS).
    d("label", 24, 24, 240, 24, "Exposure (stops)")
    d("scale", 24, 56, 480, 32, port={"name": "exposure", "default": 2.5},
      from_=0.5, to=9.5)
    d("label", 24, 112, 480, 24, port="reading")


@_case("c_colour_no_caps", "Colour Ignored", "Colour Ignored")
def _colour_no_caps(d: _Draw) -> None:
    d.project.window.bg, d.project.window.fg = "#1e1e2e", "#cdd6f4"
    red, green = "#ff0000", "#00ff00"
    d("label", 24, 24, 320, 24, "Coloured caption", bg="#313244", fg="#f5e0dc")
    d("combobox", 24, 64, 240, 32, port="choice", bg=red, fg=green,
      values=["One", "Two"])
    d("progressbar", 24, 112, 480, 24, port="progress", bg=red, fg=green)
    d("treeview", 24, 152, 480, 240, port="table", bg=red, fg=green,
      columns=["A", "B"])
    d("file_picker", 24, 416, 480, 32, port="source", bg=red, fg=green)
    d("toolbar", 528, 24, 544, 40, "Actions", bg=red, fg=green,
      buttons=["One"])
    d("notebook", 528, 88, 544, 360, "Empty tabs", bg=red, fg=green)
    d("scrubber", 528, 472, 544, 40, "Index", port="index", bg=red, fg=green)
    d("status_bar", 0, 672, 1096, 24, port="status", bg=red, fg=green)


#: The kinds c_colour_no_caps colours although they cannot take colour.
UNCOLOURABLE = ("combobox", "progressbar", "treeview", "file_picker",
                "toolbar", "notebook", "scrubber", "status_bar")


def write_all() -> List[Path]:
    """Rewrite every case file from its builder. The one supported way to
    change a case — see the module docstring."""
    written = []
    for stem, build in sorted(BUILDERS.items()):
        path = CASES_DIR / f"{stem}.gspec"
        save_gspec(path, build())
        written.append(path)
    return written


# ============================================================
# The rules a case must obey
# ============================================================

#: Tier C cases that break a rule ON PURPOSE, by rule name. A case listed here
#: must break exactly these rules: an edge case that stopped bending its rule
#: has stopped testing the edge.
BENDS: Dict[str, set] = {
    "c_float_scale": {"whole numbers"},
}

_NUMERIC_BOUNDS = ("from_", "to", "increment")


def container_of(shape: Shape, shapes: List[Shape]) -> Optional[Shape]:
    """The smallest container that fully contains ``shape``, or None.

    Worked out from the drawing alone, not from gui_layout: the point of the
    running-window check is that what was drawn inside what ends up inside it,
    and asking the layout engine which parent it picked would make that
    circular."""
    best = None
    for c in shapes:
        if c is shape or not is_container(c.kind) or c.area <= shape.area:
            continue
        if c.contains(shape) and (best is None or c.area < best.area):
            best = c
    return best


def rule_breaks(p: Project) -> List[Tuple[str, str]]:
    """(rule, message) for everything in ``p`` a case may not do."""
    out: List[Tuple[str, str]] = []

    def brk(rule: str, message: str) -> None:
        out.append((rule, message))

    if (p.canvas.w, p.canvas.h, p.canvas.grid_snap) != (CANVAS_W, CANVAS_H,
                                                        GRID):
        brk("canvas", f"canvas is {p.canvas.w}x{p.canvas.h} snap "
                      f"{p.canvas.grid_snap}, not the Designer's 1100x700/8")
    if not _PROJECT_NAME.match(p.project):
        brk("name", f"project name {p.project!r} cannot be a project "
                    f"directory")
    if p.gspec_version != required_version(p):
        brk("version", f"gspec_version {p.gspec_version} but the content "
                       f"needs {required_version(p)}")
    if not isinstance(p.requires, list) or any(
            str(r).split(".")[0] == "PySide6" for r in p.requires):
        brk("requires", f"requires {p.requires!r}: a Qt project gets PySide6 "
                        f"from its target, and the gate refuses declaring it")
    for chan in ("bg", "fg"):
        v = getattr(p.window, chan)
        if v and not _HEX.match(v):
            brk("colour", f"window {chan} {v!r} is not #rrggbb")

    zs = [s.z for s in p.shapes]
    if any(a >= b for a, b in zip(zs, zs[1:])):
        brk("order", f"z must increase in file order, got {zs}")

    # Up front, so a shape that fails an early check below still has its
    # container — otherwise it reads as a root shape and adds a false overlap.
    parent = {s.id: container_of(s, p.shapes) for s in p.shapes}
    for s in p.shapes:
        where = f"{s.kind} {s.label or s.port.get('name') or s.id[:8]!r}"
        if s.kind not in PALETTE or s.kind == GENERIC_KIND:
            brk("kind", f"{where}: not a concrete palette kind")
            continue
        if s.w <= 0 or s.h <= 0 or any(v % GRID for v in (s.x, s.y, s.w, s.h)):
            brk("grid", f"{where}: ({s.x}, {s.y}, {s.w}, {s.h}) is off the "
                        f"{GRID} px grid")
        if s.x < 0 or s.y < 0 or s.x2 > CANVAS_W or s.y2 > CANVAS_H:
            brk("inside canvas", f"{where}: reaches outside the canvas")
        for chan in ("bg", "fg"):
            v = getattr(s, chan)
            if v and not _HEX.match(v):
                brk("colour", f"{where}: {chan} {v!r} is not #rrggbb")

        schema = PALETTE[s.kind].get("prop_schema") or {}
        for key, value in s.props.items():
            if key not in schema:
                brk("props", f"{where}: {s.kind} has no prop {key!r}")
                continue
            choices = schema[key].get("choices")
            if choices and value not in choices:
                brk("props", f"{where}: {key}={value!r} not in {choices}")
            if schema[key].get("type") == "list[str]" and not (
                    isinstance(value, list)
                    and all(isinstance(v, str) for v in value)):
                brk("lists", f"{where}: {key} must be a real list of str, "
                             f"got {value!r}")
        if s.kind == "label" and s.props.get("anchor", "w") not in (
                "w", "center", "e"):
            brk("anchor", f"{where}: label anchor must be w, center or e")
        if s.kind in ("spinbox", "scale", "scrubber"):
            for key in _NUMERIC_BOUNDS:
                v = s.props.get(key)
                if key in s.props and (isinstance(v, bool)
                                       or not isinstance(v, int)):
                    brk("whole numbers", f"{where}: {key}={v!r} is not a "
                                         f"whole number")

        for other in p.shapes:
            if (other is not s and not is_container(other.kind)
                    and other.area > s.area and other.contains(s)):
                brk("containment", f"{where}: drawn inside a {other.kind}, "
                                   f"which cannot hold children")
        box = parent[s.id]
        if box is not None:
            gap = min(s.x - box.x, s.y - box.y, box.x2 - s.x2, box.y2 - s.y2)
            if gap < MARGIN:
                brk("margin", f"{where}: only {gap} px inside its {box.kind}; "
                              f"needs {MARGIN}")
            if box.z >= s.z:
                brk("order", f"{where}: drawn before its {box.kind}")

    siblings: Dict[Optional[str], List[Shape]] = defaultdict(list)
    for s in p.shapes:
        box = parent.get(s.id)
        siblings[box.id if box else None].append(s)
    for group in siblings.values():
        for i, a in enumerate(group):
            for b in group[i + 1:]:
                if a.overlaps(b):
                    brk("overlap", f"{a.kind} {a.label!r} and {b.kind} "
                                   f"{b.label!r} overlap")
    for s in p.shapes:
        if s.kind == "notebook":
            tabs = s.props.get("tabs") or []
            pages = siblings.get(s.id, [])
            if len(tabs) != len(pages):
                brk("tabs", f"notebook {s.label!r}: {len(pages)} page(s) but "
                            f"{len(tabs)} tab title(s)")
    return out


# ============================================================
# The cases on disk
# ============================================================

FILES = sorted(CASES_DIR.glob("*.gspec"))


def _tier(path: Path) -> str:
    return path.stem.split("_", 1)[0]


def _params(stems=None, xfail: Optional[Dict[str, str]] = None):
    """One param per case file, id'd by its stem. ``xfail`` maps a stem to why
    it still fails. strict, so the day one starts passing the run says so and
    the entry comes out — a known-failure list that cannot go stale.

    No case needs one on the core path (rules, generate, open, probe): every
    tier C case builds and behaves as its README line says."""
    out = []
    for path in FILES:
        if stems is not None and path.stem not in stems:
            continue
        why = (xfail or {}).get(path.stem)
        marks = [pytest.mark.xfail(reason=why, strict=True)] if why else []
        out.append(pytest.param(path, id=path.stem, marks=marks))
    return out


def test_the_cases_folder_is_not_empty_and_every_file_has_a_builder():
    """A .gspec with no builder cannot be regenerated by the one supported
    route, and a builder with no file is a case that is never run."""
    assert FILES, f"no cases in {CASES_DIR}"
    assert {p.stem for p in FILES} == set(BUILDERS)


@pytest.mark.parametrize("stem", sorted(BUILDERS))
def test_each_case_file_is_exactly_what_its_builder_writes(stem, tmp_path):
    """The files are generated, not typed. A difference means one of them was
    edited by hand — rewrite them with `python -m tests.test_qt_wireframes
    --write` after changing the builder. Compared as parsed JSON, so a line
    ending changed by git on checkout is not a difference."""
    fresh = tmp_path / f"{stem}.gspec"
    save_gspec(fresh, BUILDERS[stem]())
    on_disk = CASES_DIR / f"{stem}.gspec"
    assert (json.loads(on_disk.read_text(encoding="utf-8"))
            == json.loads(fresh.read_text(encoding="utf-8")))


def test_every_case_is_named_for_its_tier():
    """The tier is the file-name prefix, so the folder listing IS the tier
    table. A case with no tier would skip the rule its tier implies."""
    assert all(_tier(p) in ("a", "b", "c") for p in FILES), [
        p.name for p in FILES if _tier(p) not in ("a", "b", "c")]


def test_the_readme_has_one_line_per_case_and_no_other():
    """What each case exercises and what it should do lives in README.md. A
    case missing from it is a case nobody can read the expectation of."""
    text = README.read_text(encoding="utf-8")
    named = re.findall(r"`([a-c]_[a-z0-9_]+)\.gspec`", text)
    assert sorted(named) == sorted(p.stem for p in FILES)
    for path in FILES:
        project = load_gspec(path).project
        line = next(ln for ln in text.splitlines()
                    if f"`{path.stem}.gspec`" in ln)
        assert project in line, (
            f"{path.stem}: README line does not name {project!r}")


def test_the_cases_are_never_offered_to_a_model_as_worked_examples():
    """gui_examples.names() globs examples/gui/*.gspec non-recursively, and
    what it returns can be pasted into a designing model's prompt. These are
    fixtures — tier C degraded on purpose — and must not be imitated."""
    import gui_examples
    assert CASES_DIR.parent == gui_examples.EXAMPLES_DIR
    stems = {p.stem for p in FILES}
    assert not stems & set(gui_examples.names())
    prompt = gui_examples.for_prompt()
    for path in FILES:
        assert f"EXAMPLE: {path.stem}" not in prompt


@pytest.mark.parametrize("path", _params())
def test_a_case_obeys_every_rule_a_wireframe_must(path):
    """Canvas, grid, containment, margins, overlap, tab titles, whole numbers,
    real lists, colours and requires — the rules that keep layout inference on
    its main path. Tier C may bend only the rules BENDS names, and must."""
    project = load_gspec(path)
    breaks = rule_breaks(project)
    bent = BENDS.get(path.stem, set())
    unexpected = [(r, m) for r, m in breaks if r not in bent]
    assert unexpected == [], unexpected
    if bent:
        assert _tier(path) == "c", "only a tier C case may bend a rule"
        assert {r for r, _m in breaks} == bent, (
            f"{path.stem} is meant to bend {sorted(bent)} and no longer does")


# ============================================================
# Generate, as the Designer does it
# ============================================================

def _no_model(prompt: str) -> str:
    raise AssertionError("an all-typed wireframe must generate with no model "
                         "call — a model was consulted")


def _generate(path: Path, vault: Path):
    """The Designer's New + Save + Generate, for a Qt project.

    The wireframe is saved into the project exactly as loaded, so the window,
    canvas and `requires` generate reads back are the case's own."""
    from council_core import designer_project
    project = load_gspec(path)
    gui_projects.create(project.project, project.mode, vault_dir=vault,
                        toolkit="qt")
    gui_projects.save_project(project.project, project, vault_dir=vault)
    pdir = gui_projects.project_path(project.project, vault)
    result = designer_project.generate(project.project, project.shapes, pdir,
                                       vault, model_call=_no_model)
    return project, pdir, result


@pytest.mark.parametrize("path", _params())
def test_a_case_generates_a_qt_project_that_passes_every_gate(path, tmp_path):
    """Generate says nothing it should not, writes a Qt app, and the result
    passes the policy gate AS QT and compiles file by file.

    The gate is called here with toolkit="qt" rather than trusted from
    generate's own "policy:" line: generate once checked a Qt project as Tk
    and reported "policy REFUSED" for every correct one, and a test asserting
    on that line would have been testing the bug."""
    project, pdir, result = _generate(path, tmp_path / "vault")
    said = "\n".join(result.lines)
    assert result.ok and not result.blocked, said
    for line in result.lines:
        assert not line.startswith("cannot generate"), said
        assert "BLOCKED" not in line and "generate failed" not in line, said
        # Layout fallbacks: an overlap turning a grid into free placement, or
        # a shape re-parented out of a non-container. The rules exist so a
        # case never needs either; if one appears the case is testing the
        # fallback, not its widgets.
        assert not line.startswith("warning:"), said
    assert gui_projects.toolkit_of(pdir) == "qt"
    ok, errors = gui_policy.validate_dir(pdir, project.mode, project.requires,
                                         toolkit="qt")
    assert ok, errors
    sources = gui_policy.project_sources(pdir)
    written = {p.relative_to(pdir).as_posix() for p in sources}
    assert {"main.py", "app.py", "handlers.py", "ui/main_ui.py",
            "ui/ports.py"} <= written, sorted(written)
    for p in sources:
        compile(p.read_text(encoding="utf-8"), str(p), "exec")


# ============================================================
# The running window
# ============================================================

#: Module names a generated project is imported under. Every Qt test file uses
#: the same ones, so each project forgets the previous one's first.
GENERATED = ("app", "handlers", "ui", "ui.main_ui", "ui.ports", "ui.widgets")


def _forget() -> None:
    for mod in [m for m in list(sys.modules) if m in GENERATED]:
        del sys.modules[mod]


@pytest.fixture(scope="module")
def qapp():
    """The one QApplication, offscreen. Created lazily so the rule and
    generate tests above still run where PySide6 is not installed."""
    pytest.importorskip("PySide6", reason="PySide6 is not installed in this "
                                          "interpreter")
    from PySide6.QtWidgets import QApplication
    app = QApplication.instance() or QApplication([])
    yield app
    app.processEvents()


class Live:
    """A generated case, running: the App plus a way to find a shape's widget
    by what the case called it (its label, or the port name it declared)."""

    def __init__(self, ui, project: Project, pdir: Path, qapp,
                 tmp: Path) -> None:
        self.ui, self.project, self.pdir, self.qapp = ui, project, pdir, qapp
        self.tmp = tmp                       # scratch space for a probe
        self.names = gui_projects.load_manifest(pdir).widget_names

    def shape(self, label: str = "", *, port: str = "", kind: str = ""
              ) -> Shape:
        found = [s for s in self.project.shapes
                 if (not label or s.label == label)
                 and (not port or s.port.get("name") == port)
                 and (not kind or s.kind == kind)]
        assert len(found) == 1, (label, port, kind, len(found))
        return found[0]

    def widget(self, label: str = "", *, port: str = "", kind: str = ""):
        return getattr(self.ui, self.names[self.shape(label, port=port,
                                                      kind=kind).id])

    def record(self, handler: str) -> list:
        """Capture calls to ``handler``. Set on the INSTANCE: _command and
        _EventPort look the name up at the moment of the click, which is the
        contract handlers.py is written against, so an instance attribute is
        reached exactly as a HandlerMixin method would be."""
        calls: list = []
        setattr(self.ui, handler, lambda *args: calls.append(args))
        return calls

    def handler_of(self, label: str = "", *, port: str = "") -> str:
        return "on_" + self.names[self.shape(label, port=port).id]

    def main_ui(self) -> str:
        return (self.pdir / "ui" / "main_ui.py").read_text(encoding="utf-8")

    def settle(self, done: Callable[[], bool], seconds: float = 5.0) -> bool:
        """Run the event loop until ``done()`` or the deadline. The frame
        browser debounces with QTimers, so a single processEvents is not
        enough to see a folder load or a scrub land."""
        deadline = time.monotonic() + seconds
        while time.monotonic() < deadline:
            self.qapp.processEvents()
            if done():
                return True
            time.sleep(0.02)
        return done()


@contextmanager
def _opened(path: Path, tmp_path: Path, qapp):
    """Generate a case and construct its App the way main() does, offscreen,
    shown at the Designer's canvas size."""
    project, pdir, result = _generate(path, tmp_path / "vault")
    assert result.ok, result.lines
    _forget()
    sys.path.insert(0, str(pdir))
    ui = None
    try:
        from app import App
        ui = App()
        ui.resize(CANVAS_W, CANVAS_H)
        ui.show()
        qapp.processEvents()
        yield Live(ui, project, pdir, qapp, tmp_path)
    finally:
        if ui is not None:
            ui.request_close()
            qapp.processEvents()
        if str(pdir) in sys.path:
            sys.path.remove(str(pdir))
        _forget()


def _under_a_notebook(shape: Shape, shapes: List[Shape]) -> bool:
    box = container_of(shape, shapes)
    while box is not None:
        if box.kind == "notebook":
            return True
        box = container_of(box, shapes)
    return False


@pytest.mark.parametrize("path", _params())
def test_a_case_opens_as_a_qt_window_with_every_shape_where_it_was_drawn(
        path, tmp_path, qapp):
    """Construct, show, and check the window against the drawing:

      * every shape is a live widget on the App, under the container it was
        drawn inside (a tab page is reparented into the tab widget's stack,
        so "under" is isAncestorOf, not parentWidget)
      * every port the manifest recorded is declared on ui.ports
      * every widget that fires a callback has its on_<name> to reach
      * everything not tucked behind a notebook tab is on screen with a size
    """
    from PySide6.QtWidgets import QWidget
    with _opened(path, tmp_path, qapp) as live:
        ui, shapes = live.ui, live.project.shapes
        assert ui.isVisible()
        for s in shapes:
            name = live.names[s.id]
            widget = getattr(ui, name)
            assert isinstance(widget, QWidget), name
            box = container_of(s, shapes)
            holder = ui if box is None else getattr(ui, live.names[box.id])
            assert holder.isAncestorOf(widget), (
                f"{name} is not inside {holder.objectName() or holder}")
            if s.kind in COMMAND_KINDS:
                assert callable(getattr(ui, f"on_{name}", None)), name
            if not _under_a_notebook(s, shapes):
                assert widget.isVisible(), f"{name} is not on screen"
                assert widget.width() > 0 and widget.height() > 0, name
        declared = set(ui.ports._names)
        for port in gui_projects.load_manifest(live.pdir).port_names.values():
            assert port in declared, port


# ============================================================
# What each case promises (README.md, "Expected")
# ============================================================

def _trigger_menu(menubar, *path) -> None:
    """Trigger the menu item at a title path, holding every wrapper on the
    way. Measured in test_gui_emit_qt_kinds.py: letting the parent action's
    wrapper go had PySide6 invalidate the leaf ("Internal C++ object already
    deleted") while the C++ action lived on — a test artefact, not a dead
    menu item."""
    held, actions = [], menubar.actions()
    for i, title in enumerate(path):
        found = next(a for a in actions if a.text() == title)
        held.append(found)
        if i == len(path) - 1:
            found.trigger()
            return
        held.append(found.menu())
        actions = held[-1].actions()


def _login_form_probe(live: Live) -> None:
    from PySide6.QtWidgets import QLineEdit
    ports = live.ui.ports
    ports.user_name.set("ada")
    assert live.widget(port="user_name").text() == "ada"
    assert ports.user_name.get() == "ada"
    assert (live.widget(port="password").echoMode()
            == QLineEdit.EchoMode.Password)
    ports.message.set("Wrong password")
    assert live.widget(port="message").text() == "Wrong password"
    calls = live.record(live.handler_of("Sign in"))
    live.widget("Sign in").click()
    assert len(calls) == 1


def _image_viewer_probe(live: Live) -> None:
    Image = pytest.importorskip("PIL.Image")
    folder = live.tmp / "frames"
    folder.mkdir()
    for i in (1, 2, 10):
        Image.new("L", (32, 24)).save(folder / f"frame_{i}.png")
    ports = live.ui.ports
    browser = ports.browse_frame
    ports.folder.set(str(folder))
    assert live.settle(lambda: browser.count() == 3)
    assert live.settle(lambda: ports.current_file.get() == "frame_1.png")
    assert live.widget(port="view")._base is not None
    live.widget(port="frame").step(1)
    assert live.settle(lambda: ports.current_file.get() == "frame_2.png")
    assert "2 / 3" in live.widget(port="status").message.text()


def _list_editor_probe(live: Live) -> None:
    ports = live.ui.ports
    ports.items.set(["alpha", "beta"])
    assert ports.items.items() == ["alpha", "beta"]
    # A button labelled Remove cannot have a port called `remove` — the gate
    # denies that attribute — so gui_ports derives remove_button.
    assert "remove_button" in ports._names
    calls = live.record(live.handler_of("Add"))
    live.widget("Add").click()
    assert len(calls) == 1


def _toolbar_editor_probe(live: Live) -> None:
    calls = live.record("on_toolbar")
    live.widget("Main tools").buttons["Save"].click()
    assert calls == [("Save",)]
    live.ui.ports.body.set("hello")
    assert live.widget(port="body").toPlainText() == "hello"
    live.ui.ports.status.set("ready")
    assert live.widget(port="status").message.text() == "ready"


def _split_browser_probe(live: Live) -> None:
    from PySide6.QtCore import Qt
    split = live.widget("Split")
    assert split.count() == 2
    assert split.orientation() == Qt.Orientation.Horizontal
    tree = live.widget(port="files")
    assert [tree.headerItem().text(i) for i in range(3)] == [
        "Name", "Size", "Modified"]
    live.ui.ports.files.set([("a.png", "12 KB", "today")])
    assert live.ui.ports.files.rows() == [("a.png", "12 KB", "today")]


def _options_group_probe(live: Live) -> None:
    ports = live.ui.ports
    assert live.widget("Output size").title() == "Output size"
    assert ports.size.get() == "small"            # the group's first value
    live.widget("Large").click()
    assert ports.size.get() == "large"
    ports.progress.set(40)
    assert live.widget(port="progress").value() == 40
    calls = live.record(live.handler_of("Sharpen"))
    live.widget("Sharpen").click()
    assert len(calls) == 1


def _notebook_tabs_probe(live: Live) -> None:
    tabs = live.widget("Sections")
    assert tabs.count() == 3
    assert [tabs.tabText(i) for i in range(3)] == [
        "General", "Display", "Advanced"]
    assert [tabs.widget(i) for i in range(3)] == [
        live.widget("General page"), live.widget("Display page"),
        live.widget("Advanced page")]
    live.ui.ports.sections.set(2)
    assert tabs.currentIndex() == 2
    combo = live.widget(port="text_size")
    assert [combo.itemText(i) for i in range(combo.count())] == [
        "Small", "Medium", "Large"]
    spin = live.widget(port="threads")
    assert (spin.minimum(), spin.maximum()) == (1, 16)


def _paned_vertical_probe(live: Live) -> None:
    from PySide6.QtCore import Qt
    split = live.widget("Console")
    assert split.count() == 2
    assert split.orientation() == Qt.Orientation.Vertical
    live.ui.ports.output.set("build finished")
    assert "build finished" in live.widget(port="output").text.toPlainText()


def _settings_form_probe(live: Live) -> None:
    theme = live.widget(port="theme")
    assert [theme.itemText(i) for i in range(theme.count())] == [
        "Light", "Dark", "System"]
    threads = live.widget(port="threads")
    assert (threads.minimum(), threads.maximum()) == (1, 32)
    cache = live.widget(port="cache_mb")
    assert (cache.minimum(), cache.maximum(), cache.singleStep()) == (
        64, 4096, 64)
    quality = live.widget(port="quality")
    assert (quality.minimum(), quality.maximum()) == (0, 100)
    calls = live.record(live.handler_of("Apply"))
    live.widget("Apply").click()
    assert len(calls) == 1


def _dashboard_probe(live: Live) -> None:
    pytest.importorskip("matplotlib")
    chart = live.widget(port="chart")
    figure = chart.figure_for_drawing()
    figure.add_subplot(111).plot([0, 1, 2], [1, 3, 2])
    chart.redraw()
    assert chart._canvas is not None
    live.ui.ports.events.set("started")
    assert "started" in live.widget(port="events").text.toPlainText()


def _nested_containers_probe(live: Live) -> None:
    outer = live.widget("Outer")
    source, target = live.widget("Source"), live.widget("Target")
    assert outer.isAncestorOf(source) and outer.isAncestorOf(target)
    assert (source.title(), target.title()) == ("Source", "Target")
    live.ui.ports.source_path.set("C:/in")
    live.ui.ports.target_path.set("D:/out")
    assert live.widget(port="source_path").text() == "C:/in"
    assert live.widget(port="target_path").text() == "D:/out"


def _assert_packed(child, holder) -> None:
    """``child`` is its holder's sole child the way Tk packs one: it reaches
    every edge, standing off the far right and bottom by exactly the margin
    it stands off the left.

    Stated as the gaps, not as a share of the holder or as the layout's rect,
    and both of those were tried first. "80% of the holder" failed on a 66x66
    frame whose 40x40 child filled it exactly: 26 px of frame and margin is
    40% of a box that small. The layout's contentsRect() came back as
    QRect(9, 9, -18, -18) for the freeform area — a null geometry — while the
    button inside sat correctly at (11, 11, 80, 20) in its 102x42 area. The
    gaps depend on nothing but where the child actually is. The top gap is
    not compared: a group box's title sits there. Whether the HOLDER keeps a
    sensible size is a separate question, asked by
    test_a_drawn_panel_keeps_its_share_of_the_window.
    """
    g = child.geometry()
    left = g.x()
    right = holder.width() - g.x() - g.width()
    bottom = holder.height() - g.y() - g.height()
    assert child.parentWidget() is holder
    assert left <= MARGIN and abs(right - left) <= 1 \
        and abs(bottom - left) <= 1, (
            f"child at {g} in a {holder.width()}x{holder.height()} holder: "
            f"left {left}, right {right}, bottom {bottom}")


def _single_child_containers_probe(live: Live) -> None:
    """A sole child is Tk's pack(fill="both", expand=True) — including a
    button in a freeform area, which Tk would stretch to the area too."""
    for holder, child in (("Preview", dict(port="preview")),
                          ("Notes", dict(port="notes")),
                          ("Scratch", dict(label="Stamp"))):
        _assert_packed(live.widget(**child), live.widget(holder))


def _single_root_shape_probe(live: Live) -> None:
    _assert_packed(live.widget(port="picture"), live.ui)


def _menubar_dicts_probe(live: Live) -> None:
    bar = live.widget(kind="menubar")
    assert live.ui.layout().menuBar() is bar
    # Every wrapper held for the whole walk. Measured here too: reading
    # bar.actions()[0].menu().actions() in one expression raised "Internal
    # C++ object (PySide6.QtWidgets.QMenu) already deleted" on one run and
    # not on another — the temporary QAction wrapper's lifetime, not the menu.
    held = bar.actions()
    assert [a.text() for a in held] == ["File", "Edit", "Help"]
    file_menu = held[0].menu()
    items = file_menu.actions()
    assert [(a.text(), a.isSeparator()) for a in items] == [
        ("New", False), ("Open", False), ("", True), ("Quit", False)]
    calls = live.record("on_menu")
    _trigger_menu(bar, "File", "Open")
    _trigger_menu(bar, "Edit", "Transform", "Upper case")
    assert calls == [("Open",), ("Upper case",)]


def _menubar_titles_probe(live: Live) -> None:
    bar = live.widget(kind="menubar")
    assert live.ui.layout().menuBar() is bar
    held = bar.actions()                   # held: see _menubar_dicts_probe
    assert [a.text() for a in held] == ["File", "View", "Help"]
    menus = [a.menu() for a in held]
    assert [m.actions() for m in menus] == [[], [], []]
    calls = live.record(live.handler_of("Go"))
    live.widget("Go").click()
    assert len(calls) == 1


def _float_scale_probe(live: Live) -> None:
    """QSlider holds whole numbers, so 0.5..9.5 becomes 0..9 and a default of
    2.5 shows 2 — and the generated file says so, which is the difference
    between a degradation and a silent bug."""
    slider = live.widget(port="exposure")
    assert (slider.minimum(), slider.maximum()) == (0, 9)
    assert slider.value() == 2
    assert live.ui.ports.exposure.get() == 2.0
    src = live.main_ui()
    assert "0.5 is truncated to 0" in src
    assert "9.5 is truncated to 9" in src


def _colour_no_caps_probe(live: Live) -> None:
    """A colour on a kind that cannot take one is dropped, not half-applied
    and not fatal — and the one kind here that CAN take colour still gets
    its own."""
    for s in live.project.shapes:
        if s.kind in UNCOLOURABLE:
            widget = getattr(live.ui, live.names[s.id])
            assert widget.styleSheet() == "", s.kind
    assert "#313244" in live.widget("Coloured caption").styleSheet()
    assert "#ff0000" not in live.main_ui()


#: stem -> the check behind that case's README "Expected" column.
PROBES: Dict[str, Callable] = {
    "a_login_form": _login_form_probe,
    "a_image_viewer": _image_viewer_probe,
    "a_list_editor": _list_editor_probe,
    "b_toolbar_editor": _toolbar_editor_probe,
    "b_split_browser": _split_browser_probe,
    "b_options_group": _options_group_probe,
    "b_notebook_tabs": _notebook_tabs_probe,
    "b_paned_vertical": _paned_vertical_probe,
    "b_settings_form": _settings_form_probe,
    "b_dashboard": _dashboard_probe,
    "b_nested_containers": _nested_containers_probe,
    "b_single_child_containers": _single_child_containers_probe,
    "b_single_root_shape": _single_root_shape_probe,
    "c_menubar_dicts": _menubar_dicts_probe,
    "c_menubar_titles": _menubar_titles_probe,
    "c_float_scale": _float_scale_probe,
    "c_colour_no_caps": _colour_no_caps_probe,
}


def test_every_case_has_a_probe_for_its_expected_outcome():
    assert set(PROBES) == {p.stem for p in FILES}


@pytest.mark.parametrize("path", _params(PROBES))
def test_a_case_does_what_its_readme_line_says(path, tmp_path, qapp):
    with _opened(path, tmp_path, qapp) as live:
        PROBES[path.stem](live)


# ============================================================
# Does the window look like the drawing?
# ============================================================
#
# Everything above asks whether a case builds, opens and works. These ask the
# question a user asks first — did I get what I drew — for the few places the
# answer was measured to be NO ON QT ONLY. Each loss below was checked against
# the Tk target rendering the same file at the same 1100x700 (scratch probe,
# tk.Toplevel + update()), so a loss both toolkits share is gui_layout's and is
# not pinned here: b_dashboard's chart keeps 0.51 of its drawn width on Tk and
# 0.48 on Qt, because its full-width log pane makes every column elastic.
#
# Strict xfails: the day a fix lands, the XPASS fails the run and the entry
# comes out, so the list cannot go stale.

#: (case, the shape, the least share of its drawn width AND height it must keep
#: with the window at the drawn size, why it does not yet — or None).
DRAWN_SHARE = [
    # Controls: the measure itself is sound where nothing is wrong.
    ("b_toolbar_editor", dict(port="body"), 0.75, None),
    ("b_single_root_shape", dict(port="picture"), 0.75, None),
    ("b_paned_vertical", dict(label="Console"), 0.75, None),
    ("b_nested_containers", dict(port="source_files"), 0.75, None),
    ("b_notebook_tabs", dict(label="Sections"), 0.75, None),
    # 0.4, not 0.75: gui_layout calls this frame "fixed" (one of three
    # similar panels in a row reads as a button row), so neither toolkit
    # stretches it. Tk still keeps 1.14 x 0.48 of the drawing.
    # Was a strict xfail: "Qt collapses a non-stretching frame to its child's
    # size hint, and the Qt ImageCanvas hints 40x40 where Tk's canvas asks
    # for 378x265: measured, this 336x560 frame renders 66x66 on Qt and
    # 382x269 on Tk". Fixed by giving the canvas Tk's request as its size
    # hint (_Viewport.sizeHint): measured after, 404x291 — 1.20 x 0.52, the
    # 22 px over Tk being QGridLayout's default contents margins.
    ("b_single_child_containers", dict(label="Preview"), 0.4, None),
    # Was a strict xfail: "setMenuBar takes the menubar out of the root grid,
    # but the grid keeps the stretch its columns were given for the menubar —
    # two EMPTY elastic columns either side of the text. Measured: the text
    # gets 356 of 1100 px; setting those two stretches to 0 in a throwaway
    # copy gives it 1074". Fixed in gui_emit_qt._lift_menu_bar: measured
    # after, 1074x613. (Tk has no number to compare: its target grids the
    # tk.Menu and dies with "can't manage ...: it's a top-level window".)
    ("c_menubar_dicts", dict(port="document"), 0.75, None),
    ("c_colour_no_caps", dict(label="Empty tabs"), 0.75,
     "QGridLayout ignores a size hint in a stretched column — only minimums "
     "count there (Qt's smartSizeHint) — where Tk's weight shares out only "
     "the space LEFT after every request. So the empty notebook, whose "
     "column is one of seven gui_layout made elastic, gets a seventh of the "
     "width. Measured at the drawn 1100x700: 199x280 on Qt, 563x309 on Tk. "
     "Its drawn size used to be a setMinimumSize floor, which kept it "
     "544x360 by holding the window at 1100x780 (see TOO_BIG's history)"),
]


def _share_params():
    out = []
    for stem, selector, least, why in DRAWN_SHARE:
        marks = [pytest.mark.xfail(reason=why, strict=True)] if why else []
        what = "-".join(str(v) for v in selector.values())
        out.append(pytest.param(stem, selector, least, marks=marks,
                                id=f"{stem}:{what}"))
    return out


@pytest.mark.parametrize("stem, selector, least", _share_params())
def test_a_drawn_panel_keeps_its_share_of_the_window(stem, selector, least,
                                                     tmp_path, qapp):
    """With the window at the size it was drawn on, a panel keeps at least
    ``least`` of its drawn width AND height. See DRAWN_SHARE for each entry's
    threshold and, where Qt falls short, the measured reason."""
    path = CASES_DIR / f"{stem}.gspec"
    with _opened(path, tmp_path, qapp) as live:
        shape = live.shape(**selector)
        widget = live.widget(**selector)
        share = (widget.width() / shape.w, widget.height() / shape.h)
        assert min(share) >= least, (
            f"drawn {shape.w}x{shape.h}, got {widget.width()}x"
            f"{widget.height()} — {share[0]:.2f} x {share[1]:.2f} of it")


#: Cases whose window cannot be shown at the size they were drawn on.
#:
#: Empty now. c_colour_no_caps was here as a strict xfail: "an EMPTY
#: container's drawn size is emitted as setMinimumSize — a hard floor on Qt,
#: where Tk's configure(width, height) is only a request — so the empty
#: 544x360 notebook forces the window to 1100x780. Measured: removing that one
#: line in a throwaway copy opens it at 1100x700". The drawn size is now a
#: size hint (the generated _requested helper): measured after, the window
#: opens at 1100x700 and its minimum fell from 836x780 to 491x594.
TOO_BIG: Dict[str, str] = {}


@pytest.mark.parametrize("path", _params(xfail=TOO_BIG))
def test_a_case_window_opens_at_the_size_it_was_drawn_on(path, tmp_path, qapp):
    """A window resized to the canvas it was drawn on must BE that size. One
    that insists on being bigger has a floor somewhere the drawing did not
    ask for, and on a smaller screen it runs off the edge."""
    with _opened(path, tmp_path, qapp) as live:
        assert (live.ui.width(), live.ui.height()) == (CANVAS_W, CANVAS_H)


#: What README.md writes on a case's line for a loss pinned above.
KNOWN_LOSS = "**Known Qt loss (strict xfail):**"


def test_the_readme_names_exactly_the_losses_pinned_as_strict_xfails():
    """The strict xfails above cannot go stale — an XPASS fails the run — but
    the README line describing each one could, and did: three lines still
    said "Known Qt loss (strict xfail)" for b_single_child_containers,
    c_menubar_dicts and c_colour_no_caps's 1100x780 window after all three
    were fixed, and the one loss still pinned — c_colour_no_caps's empty
    notebook, Empty tabs — was described nowhere. So the marked cases must be
    exactly the pinned ones, and a DRAWN_SHARE loss must name its shape."""
    lines = {m.group(1): ln for ln in README.read_text(
        encoding="utf-8").splitlines()
        for m in [re.search(r"^\| `([a-c]_[a-z0-9_]+)\.gspec`", ln)] if m}
    pinned = {stem for stem, _sel, _least, why in DRAWN_SHARE if why}
    pinned |= set(TOO_BIG)
    marked = {stem for stem, ln in lines.items() if KNOWN_LOSS in ln}
    assert marked == pinned, (f"marked in README but not pinned: "
                              f"{sorted(marked - pinned)}; pinned but not "
                              f"marked: {sorted(pinned - marked)}")
    for stem, selector, _least, why in DRAWN_SHARE:
        if why:
            loss = lines[stem].split(KNOWN_LOSS, 1)[1]
            for value in selector.values():
                assert str(value) in loss, (stem, value)


if __name__ == "__main__":
    if "--write" not in sys.argv[1:]:
        raise SystemExit("usage: python -m tests.test_qt_wireframes --write")
    for written in write_all():
        print(f"wrote {written.relative_to(ROOT).as_posix()}")
